# Generated by Django 3.2.15 on 2023-05-16 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP Address')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_organization_type_related', related_query_name='c_organization_types', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_organization_type_related', related_query_name='u_organization_types', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'og_types',
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP Address')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ordering', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordering')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_organization_region_related', related_query_name='c_organization_regions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='organization_region_related', related_query_name='organization_regions', to='auth.Group')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_organization_region_related', related_query_name='u_organization_regions', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='organization_region_related', related_query_name='organization_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'og_region',
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_division', models.BooleanField(default=False)),
                ('is_district', models.BooleanField(default=False)),
                ('is_tehsil', models.BooleanField(default=False)),
                ('lft', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('rght', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('tree_id', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('mptt_level', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_organization_city_related', related_query_name='c_organization_citys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, related_name='organization_city_related', related_query_name='organization_citys', to='auth.Group')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='children', to='organization.city')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_city_related', related_query_name='organization_citys', to='organization.region')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_organization_city_related', related_query_name='u_organization_citys', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('users', models.ManyToManyField(blank=True, related_name='organization_city_related', related_query_name='organization_citys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'og_cities',
                'ordering': ['mptt_level'],
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP Address')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_organization_related', related_query_name='organization_organizations', to='organization.city')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='c_organization_organization_related', related_query_name='c_organization_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, related_name='organization_organization_related', related_query_name='organization_organizations', to='auth.Group')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_organization_related', related_query_name='organization_organizations', to='organization.region')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_organization_related', related_query_name='organization_organizations', to='organization.type')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='u_organization_organization_related', related_query_name='u_organization_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('users', models.ManyToManyField(blank=True, related_name='organization_organization_related', related_query_name='organization_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'og_organizations',
                'unique_together': {('region', 'city', 'type', 'code')},
            },
        ),
    ]
