# Generated by Django 3.2.15 on 2023-05-24 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organization_region_related', related_query_name='organization_regions', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='region',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='organization_region_related', related_query_name='organization_regions', to=settings.AUTH_USER_MODEL),
        ),
    ]
