# Generated by Django 3.2.15 on 2023-06-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230524_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskaction',
            options={'permissions': [('can_delete_flag', 'Can delete flag')], 'verbose_name': 'Task Action', 'verbose_name_plural': 'Task Actions'},
        ),
    ]
