# Generated by Django 3.2.15 on 2023-06-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_taskaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskaction',
            options={'verbose_name': 'Task Action', 'verbose_name_plural': 'Task Actions'},
        ),
    ]
