# Generated by Django 3.2.15 on 2024-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_taskaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created On'),
        ),
    ]
