# Generated by Django 3.2.15 on 2023-05-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CADetail',
            fields=[
            ],
            options={
                'verbose_name': 'Project Details',
                'verbose_name_plural': 'Project Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='DashboardPdh',
            fields=[
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
            ],
            options={
                'verbose_name': 'Organizational Hierarchy',
                'verbose_name_plural': 'Organizational Hierarchy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='ProjectDirectorHousing',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.taskaction',),
        ),
        migrations.CreateModel(
            name='RectifiedFlag',
            fields=[
            ],
            options={
                'verbose_name': 'Rectified Flags',
                'verbose_name_plural': 'Rectified Flags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.taskaction',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='TaskActionList',
            fields=[
            ],
            options={
                'verbose_name': 'Flags',
                'verbose_name_plural': 'Flags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.taskaction',),
        ),
    ]
