# Generated by Django 3.2.15 on 2023-06-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactionlist',
            options={'permissions': [('can_delete_flag', 'Can delete flag')], 'verbose_name': 'Flags', 'verbose_name_plural': 'Flags'},
        ),
    ]
