# Generated by Django 3.2.15 on 2023-05-16 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import utils.Upload
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('name_of_company', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_reg_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Company/Firm Registration No')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Serial Number')),
                ('fax', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ntn', models.CharField(max_length=50, null=True, unique=True, verbose_name='National Tax Number (NTN)')),
                ('ntn_certificate_no', models.CharField(max_length=50, null=True, verbose_name='Certificate No')),
                ('ntn_valid_upto', models.DateField(null=True, verbose_name='Valid Upto')),
                ('fbr_registration', models.CharField(max_length=50, null=True, verbose_name='FBR Registration')),
                ('fbr_certificate_no', models.CharField(max_length=50, null=True, verbose_name='Certificate No')),
                ('fbr_valid_upto', models.DateField(null=True, verbose_name='Valid Upto')),
                ('strn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sales Tax Registration Number (STRN)')),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='GST No.')),
                ('pec_reg_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='PEC Reg No')),
                ('pec_category', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='PEC Category')),
                ('established_on', models.DateField(null=True, verbose_name='Established In')),
                ('prefix_consumerid', models.CharField(max_length=4, verbose_name='Prefix ECommerce ID')),
                ('address_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('ownership', models.BooleanField(blank=True, default=False, null=True, verbose_name='System Ownership')),
                ('logo', models.FileField(blank=True, max_length=250, null=True, upload_to=utils.Upload.Upload)),
                ('category_applied', models.CharField(blank=True, choices=[('C-A', 'C-A'), ('C-B', 'C-B'), ('C-1', 'C-1'), ('C-2', 'C-2'), ('C-3', 'C-3'), ('C-4', 'C-4'), ('C-5', 'C-5'), ('C-6', 'C-6'), ('C-7', 'C-7')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_company_vendorcompany_related', related_query_name='vendor_company_vendorcompanys', to='organization.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='c_vendor_company_vendorcompany_related', related_query_name='c_vendor_company_vendorcompanys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_company_vendorcompany_related', related_query_name='vendor_company_vendorcompanys', to='organization.region')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='status_vendor_company_vendorcompany_related', related_query_name='status_vendor_company_vendorcompanys', to='core.systemstatus', verbose_name='Status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='u_vendor_company_vendorcompany_related', related_query_name='u_vendor_company_vendorcompanys', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='v_vendor_company_vendorcompany_related', related_query_name='v_vendor_company_vendorcompanys', to=settings.AUTH_USER_MODEL, verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'ven_companies',
                'unique_together': {('ntn', 'code')},
            },
        ),
    ]
