# Generated by Django 3.2.15 on 2023-05-16 10:51

import colorfield.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mptt.fields
import utils.Upload
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('whitelist_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Whitelist IP Address')),
                ('avatar', models.FileField(blank=True, max_length=250, null=True, upload_to=utils.Upload.Upload, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Picture')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('password_change_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('device_token', models.CharField(blank=True, max_length=250, null=True)),
                ('device_uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('is_mobile_user', models.BooleanField(default=False, help_text='Designates whether the user can log into mobile app.', verbose_name='Dash Mob status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_core_user_related', related_query_name='c_core_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip Address')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('system_code', models.CharField(max_length=100, unique=True)),
                ('lft', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('rght', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('tree_id', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('mptt_level', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_core_systemtype_related', related_query_name='c_core_systemtypes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('desg_level', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='des_level_children', to='core.systemtype')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='children', to='core.systemtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_core_systemtype_related', related_query_name='u_core_systemtypes', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'System Type',
                'verbose_name_plural': 'System Types',
                'db_table': 'core_types',
                'ordering': ['mptt_level'],
                'unique_together': {('parent', 'system_code')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
            ],
            options={
                'verbose_name': 'Users Roles & Permissions',
                'verbose_name_plural': 'Users Roles & Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeHierarchy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip Address')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_core_usertypehierarchy_related', related_query_name='c_core_usertypehierarchys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('group_user_types', models.ManyToManyField(blank=True, null=True, related_name='gut_core_usertypehierarchy_related', related_query_name='gut_core_usertypehierarchys', to='core.SystemType')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_core_usertypehierarchy_related', related_query_name='u_core_usertypehierarchys', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ut_core_usertypehierarchy_related', related_query_name='ut_core_usertypehierarchys', to='core.systemtype', verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'Hierarchy',
                'verbose_name_plural': 'Hierarchy',
                'db_table': 'core_user_type_hierarchy',
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip Address')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('system_code', models.CharField(max_length=100, unique=True)),
                ('is_panic', models.BooleanField(blank=True, default=False, null=True, verbose_name='Panic Status')),
                ('lft', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('rght', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('tree_id', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('mptt_level', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_core_systemstatus_related', related_query_name='c_core_systemstatuss', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='children', to='core.systemstatus')),
                ('type', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_systemstatus_related', related_query_name='core_systemstatuss', to='core.systemtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_core_systemstatus_related', related_query_name='u_core_systemstatuss', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'core_status',
                'ordering': ['mptt_level'],
                'unique_together': {('parent', 'system_code')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_core_user_related', related_query_name='core_users', to='core.systemstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_core_user_related', related_query_name='u_core_users', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.systemtype',),
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.systemstatus',),
        ),
        migrations.CreateModel(
            name='OrganizationHierarchy',
            fields=[
            ],
            options={
                'verbose_name': 'Organization Hierarchy',
                'verbose_name_plural': 'Organization Hierarchy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.systemtype',),
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.systemtype',),
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.systemtype',),
        ),
        migrations.CreateModel(
            name='RoleExtra',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='core_roleextra_related', related_query_name='core_roleextras', serialize=False, to='core.role')),
                ('system_code', models.CharField(blank=True, max_length=100, null=True)),
                ('society_id', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_core_roleextra_related', related_query_name='c_core_roleextras', to='core.superuser', verbose_name='Created By')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_core_roleextra_related', related_query_name='c_core_roleextras', to='core.usertype', verbose_name='Role Type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_core_roleextra_related', related_query_name='u_core_roleextras', to='core.superuser', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Role Extra Info',
                'verbose_name_plural': 'Role Extra Info',
                'db_table': 'core_role_extra',
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('android', 'Android'), ('ios', 'IOS')], default='android', max_length=20)),
                ('version', models.PositiveSmallIntegerField(verbose_name='Version')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_core_appversion_related', related_query_name='c_core_appversions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_core_appversion_related', related_query_name='u_core_appversions', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'db_table': 'core_app_version',
                'unique_together': {('type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AppMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='far fa-file-alt opacity-4 d-block text-150 my-15', max_length=100, null=True)),
                ('lft', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('rght', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('tree_id', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('mptt_level', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('type', models.CharField(choices=[('app_label', 'App_Label'), ('model', 'Model')], max_length=20)),
                ('content_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_appmenu_related', related_query_name='core_appmenus', to='core.contenttype', verbose_name='Content Type')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='children', to='core.appmenu')),
            ],
            options={
                'verbose_name': 'App Menu',
                'verbose_name_plural': 'App Menu',
                'db_table': 'core_app_menu',
                'ordering': ['mptt_level'],
                'unique_together': {('name', 'parent', 'content_type')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_core_user_related', related_query_name='gender_core_users', to='core.gender', verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_user_related', related_query_name='core_users', to='core.maritalstatus', verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_core_user_related', related_query_name='title_core_users', to='core.title', verbose_name='Prefix Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_user_related', related_query_name='core_users', to='core.usertype', verbose_name='User Type'),
        ),
    ]
