# Generated by Django 3.2.15 on 2023-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypehierarchy',
            name='group_user_types',
            field=models.ManyToManyField(blank=True, related_name='gut_core_usertypehierarchy_related', related_query_name='gut_core_usertypehierarchys', to='core.SystemType'),
        ),
    ]
