# Generated by Django 3.2.15 on 2023-05-29 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usertypehierarchy_group_user_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentableUserType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip Address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_core_commentableusertype_related', related_query_name='c_core_commentableusertypes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_core_commentableusertype_related', related_query_name='u_core_commentableusertypes', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user_types', models.ManyToManyField(related_name='ut_core_commentableusertype_related', related_query_name='ut_core_commentableusertypes', to='core.UserType', verbose_name='User Types')),
            ],
            options={
                'verbose_name': 'Allowed To Comment User',
                'verbose_name_plural': 'Allowed To Comment Users',
                'db_table': 'core_commentable_user_type',
            },
        ),
    ]
