# Generated by Django 3.2.15 on 2023-05-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commentableusertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentableUserType',
        ),
    ]
