# Generated by Django 3.2.15 on 2023-08-02 10:43

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.systemstatus'),
        ),
        migrations.AlterField(
            model_name='systemtype',
            name='desg_level',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='des_level_children', to='core.systemtype'),
        ),
        migrations.AlterField(
            model_name='systemtype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.systemtype'),
        ),
    ]
