# Generated by Django 3.2.15 on 2023-08-02 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230802_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_core_user_related', related_query_name='c_core_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_core_user_related', related_query_name='gender_core_users', to='core.gender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_related', related_query_name='core_users', to='core.maritalstatus', verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_core_user_related', related_query_name='core_users', to='core.systemstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_core_user_related', related_query_name='title_core_users', to='core.title', verbose_name='Prefix Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_related', related_query_name='core_users', to='core.usertype', verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_core_user_related', related_query_name='u_core_users', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
