# Generated by Django 3.2.15 on 2023-08-02 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230802_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtype',
            name='desg_level',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='des_level_children', to='core.systemtype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
