# Generated by Django 3.2.15 on 2023-08-02 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230802_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.manager.EmptyManager, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
