# Generated by Django 3.2.15 on 2023-09-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20230524_1307'),
        ('core', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_userprofile_related', related_query_name='core_userprofiles', to='organization.city'),
        ),
    ]
